=begin
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It     demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompuertusController do
  login_user

  describe "POST create" do
    context "with valid attributes" do
      it "creates a new compuertu compuerta_inclu" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
        expect{
          post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_inclu", :posicion => "0"}
        }.to change(Compuertu,:count).by(1)
      end

      it "redirects to the new compuertu compuerta_inclu" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
        post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_inclu", :posicion => "0"}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "creates a new compuertu compuerta_exclu" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "2")
        expect{
          post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_exclu", :posicion => "0"}
        }.to change(Compuertu,:count).by(1)
      end

      it "redirects to the new compuertu compuerta_exclu" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "2")
        post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_exclu", :posicion => "0"}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "creates a new compuertu compuerta_para" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "3")
        expect{
          post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_para", :posicion => "0"}
        }.to change(Compuertu,:count).by(1)
      end

      it "redirects to the new compuertu compuerta_para" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "3")
        post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_exclu", :posicion => "0"}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "renames a compuertus compuerta_inclu" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
        compuertuUpdate = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
        post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_inclu", :posicion => "0"}
        compuertuBD = Compuertu.last
        myjstreeBD = MyJsTree.last
        post :updateName, {:nombre => compuertuUpdate.nombre, :nodo_id => myjstreeBD.id, :id => compuertuBD.id}
        compuertuBDUpd = Compuertu.find_by_id(compuertuBD.id)
        myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
        compuertuBDUpd.nombre.should eq(compuertuUpdate.nombre)
        myjstreeBDUpd.title.should eq(compuertuUpdate.nombre)
      end

      it "redirects to the rename compuertus compuerta_inclu" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.create(:compuertu, plantilla_id: plantilla.id)
        compuertuUpdate = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
        post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_inclu", :posicion => "0"}
        compuertuBD = Compuertu.last
        myjstreeBD = MyJsTree.last
        post :updateName, {:nombre => compuertuUpdate.nombre, :nodo_id => myjstreeBD.id, :id => compuertuBD.id}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "renames a compuertus compuerta_exclu" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "2")
        compuertuUpdate = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
        post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_exclu", :posicion => "0"}
        compuertuBD = Compuertu.last
        myjstreeBD = MyJsTree.last
        post :updateName, {:nombre => compuertuUpdate.nombre, :nodo_id => myjstreeBD.id, :id => compuertuBD.id}
        compuertuBDUpd = Compuertu.find_by_id(compuertuBD.id)
        myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
        compuertuBDUpd.nombre.should eq(compuertuUpdate.nombre)
        myjstreeBDUpd.title.should eq(compuertuUpdate.nombre)
      end

      it "redirects to the rename compuertus compuerta_exclu" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "2")
        compuertuUpdate = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
        post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_exclu", :posicion => "0"}
        compuertuBD = Compuertu.last
        myjstreeBD = MyJsTree.last
        post :updateName, {:nombre => compuertuUpdate.nombre, :nodo_id => myjstreeBD.id, :id => compuertuBD.id}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "renames a compuertus compuerta_para" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "3")
        compuertuUpdate = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
        post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_para", :posicion => "0"}
        compuertuBD = Compuertu.last
        myjstreeBD = MyJsTree.last
        post :updateName, {:nombre => compuertuUpdate.nombre, :nodo_id => myjstreeBD.id, :id => compuertuBD.id}
        compuertuBDUpd = Compuertu.find_by_id(compuertuBD.id)
        myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
        compuertuBDUpd.nombre.should eq(compuertuUpdate.nombre)
        myjstreeBDUpd.title.should eq(compuertuUpdate.nombre)
      end

      it "redirects to the rename compuertus compuerta_para" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "3")
        compuertuUpdate = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
        post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_para", :posicion => "0"}
        compuertuBD = Compuertu.last
        myjstreeBD = MyJsTree.last
        post :updateName, {:nombre => compuertuUpdate.nombre, :nodo_id => myjstreeBD.id, :id => compuertuBD.id}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      #it "destroy a actividad compuerta_inclu" do
      #  tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
      #  plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
      #  #crea arbol
      #  myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree.save
      #  myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree1.save
      #  evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
      #  evento.save
      #  compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
      #  compuertuUpdate = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
      #  post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_para", :posicion => "0"}
      #  compuertuBD = Compuertu.last
      #  myjstreeBD = MyJsTree.last
      #  post :destroy, {:id => compuertuBD.id}
      #  compuertuBDUpd = Compuertu.find_by_id(compuertuBD.id)
      #  myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
      #  compuertuBDUpd.should be_nil
      #  myjstreeBDUpd.should be_nil
      #end

      #it "redirects to the destroy actividad compuerta_inclu" do
      #  tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
      #  plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
      #  #crea arbol
      #  myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree.save
      #  myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree1.save
      #  evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
      #  evento.save
      #  compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
      #  compuertuUpdate = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id)
      #  post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_inclu", :posicion => "0"}
      #  compuertuBD = Compuertu.last
      #  myjstreeBD = MyJsTree.last
      #  post :destroy, {:id => compuertuBD.id}
      #  response.should render_template(:text => "true")
      #end
    end

    context "with valid attributes" do
      #it "destroy a actividad compuerta_exclu" do
      #  tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
      #  plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
      #  #crea arbol
      #  myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree.save
      #  myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree1.save
      #  evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
      #  evento.save
      #  compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "2")
      #  post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_exclu", :posicion => "0"}
      #  compuertuBD = Compuertu.last
      #  myjstreeBD = MyJsTree.last
      #  post :destroy, {:id => compuertuBD.id}
      #  compuertuBDUpd = Compuertu.find_by_id(compuertuBD.id)
      #  myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
      #  compuertuBDUpd.should be_nil
      #  myjstreeBDUpd.should be_nil
      #end

      #it "redirects to the destroy actividad compuerta_exclu" do
      #  tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
      #  plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
      #  #crea arbol
      #  myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree.save
      #  myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree1.save
      #  evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
      #  evento.save
      #  compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "3")
      #  post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_exclu", :posicion => "0"}
      #  compuertuBD = Compuertu.last
      #  myjstreeBD = MyJsTree.last
      #  post :destroy, {:id => compuertuBD.id}
      #  response.should render_template(:text => "true")
      #end
    end

    context "with valid attributes" do
      #it "destroy a actividad compuerta_para" do
      #  tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
      #  plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
      #  #crea arbol
      #  myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree.save
      #  myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree1.save
      #  evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
      #  evento.save
      #  compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "3")
      #  post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_para", :posicion => "0"}
      #  compuertuBD = Compuertu.last
      #  myjstreeBD = MyJsTree.last
      #  post :destroy, {:id => compuertuBD.id}
      #  compuertuBDUpd = Compuertu.find_by_id(compuertuBD.id)
      #  myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
      #  compuertuBDUpd.should be_nil
      #  myjstreeBDUpd.should be_nil
      #end

      #it "redirects to the destroy actividad compuerta_para" do
      #  tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
      #  plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
      #  #crea arbol
      #  myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree.save
      #  myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
      #  myjstree1.save
      #  evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
      #  evento.save
      #  compuertu = FactoryGirl.build(:compuertu, plantilla_id: plantilla.id, tipo: "3")
      #  post :create, {compuertu: FactoryGirl.attributes_for(:compuertu, plantilla_id: plantilla.id, tipo: compuertu.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => compuertu.nombre, :nodo_tipo => "compuerta_para", :posicion => "0"}
      #  compuertuBD = Compuertu.last
      #  myjstreeBD = MyJsTree.last
      #  post :destroy, {:id => compuertuBD.id}
      #  response.should render_template(:text => "true")
      #end
    end

  end
end
