=begin
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It     demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventosController do
  login_user

  describe "POST create" do
    context "with valid attributes" do
      it "creates a new evento evento_intermedio" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.build(:evento, plantilla_id: plantilla.id)
        expect{
          post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_intermedio", :posicion => "0"}
        }.to change(Evento,:count).by(1)
      end

      it "redirects to the new evento evento_intermedio" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.build(:evento, plantilla_id: plantilla.id)
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_intermedio", :posicion => "0"}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "creates a new evento evento_fin" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.build(:evento, plantilla_id: plantilla.id, tipo: "2")
        expect{
          post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id, tipo: evento.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_fin", :posicion => "0"}
        }.to change(Evento,:count).by(1)
      end

      it "redirects to the new evento evento_fin" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.build(:evento, plantilla_id: plantilla.id, tipo: "2")
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id, tipo: evento.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_fin", :posicion => "0"}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "renames a evento evento_intermedio" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.create(:evento, plantilla_id: plantilla.id)
        eventoUpdate = FactoryGirl.build(:evento, plantilla_id: plantilla.id)
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_intermedio", :posicion => "0"}
        eventoBD = Evento.find_by_id(evento.id + 1)
        myjstreeBD = MyJsTree.last()
        post :updateName, {:nombre => eventoUpdate.nombre, :nodo_id => myjstreeBD.id, :id => eventoBD.id}
        eventoBDUpd = Evento.find_by_id(eventoBD.id)
        myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
        eventoBDUpd.nombre.should eq(eventoUpdate.nombre)
        myjstreeBDUpd.title.should eq(eventoUpdate.nombre)
      end

      it "redirects to the rename evento evento_intermedio" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.create(:evento, plantilla_id: plantilla.id)
        eventoUpdate = FactoryGirl.build(:evento, plantilla_id: plantilla.id)
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_intermedio", :posicion => "0"}
        eventoBD = Evento.find_by_id(evento.id + 1)
        myjstreeBD = MyJsTree.last()
        post :updateName, {:nombre => eventoUpdate.nombre, :nodo_id => myjstreeBD.id, :id => eventoBD.id}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "renames a evento evento_fin" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.create(:evento, plantilla_id: plantilla.id)
        eventoUpdate = FactoryGirl.build(:evento, plantilla_id: plantilla.id, tipo: "2")
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id, tipo: evento.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_fin", :posicion => "0"}
        eventoBD = Evento.find_by_id(evento.id + 1)
        myjstreeBD = MyJsTree.last()
        post :updateName, {:nombre => eventoUpdate.nombre, :nodo_id => myjstreeBD.id, :id => eventoBD.id}
        eventoBDUpd = Evento.find_by_id(eventoBD.id)
        myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
        eventoBDUpd.nombre.should eq(eventoUpdate.nombre)
        myjstreeBDUpd.title.should eq(eventoUpdate.nombre)
      end

      it "redirects to the rename evento evento_fin" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.create(:evento, plantilla_id: plantilla.id, tipo: "2")
        eventoUpdate = FactoryGirl.build(:evento, plantilla_id: plantilla.id)
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id, tipo: evento.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_fin", :posicion => "0"}
        eventoBD = Evento.find_by_id(evento.id + 1)
        myjstreeBD = MyJsTree.last()
        post :updateName, {:nombre => eventoUpdate.nombre, :nodo_id => myjstreeBD.id, :id => eventoBD.id}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "destroy a evento evento_intermedio" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.create(:evento, plantilla_id: plantilla.id)
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_intermedio", :posicion => "0"}
        eventoBD = Evento.find_by_id(evento.id + 1)
        myjstreeBD = MyJsTree.last()
        post :destroy, {:id => eventoBD.id}
        eventoBDUpd = Evento.find_by_id(eventoBD.id)
        myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
        eventoBDUpd.should be_nil
        myjstreeBDUpd.should be_nil
      end

      it "redirects to the destroy evento evento_intermedio" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.create(:evento, plantilla_id: plantilla.id)
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_intermedio", :posicion => "0"}
        eventoBD = Evento.find_by_id(evento.id + 1)
        myjstreeBD = MyJsTree.last()
        post :destroy, {:id => eventoBD.id}
        response.should render_template(:text => "true")
      end
    end

    context "with valid attributes" do
      it "destroy a evento evento_fin" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.create(:evento, plantilla_id: plantilla.id, tipo: "2")
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id, tipo: evento.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_fin", :posicion => "0"}
        eventoBD = Evento.find_by_id(evento.id + 1)
        myjstreeBD = MyJsTree.last()
        post :destroy, {:id => eventoBD.id}
        eventoBDUpd = Evento.find_by_id(eventoBD.id)
        myjstreeBDUpd = MyJsTree.find_by_id(myjstreeBD.id)
        eventoBDUpd.should be_nil
        myjstreeBDUpd.should be_nil
      end

      it "redirects to the destroy evento evento_fin" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        #crea arbol
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        evento=Evento.new(:nombre=>'Inicio',:descripcion=> '',:tipo=> '1',:plantilla_id=> plantilla.id,:my_js_tree_id=> MyJsTree.last().id)
        evento.save
        evento = FactoryGirl.create(:evento, plantilla_id: plantilla.id, tipo: "2")
        post :create, {evento: FactoryGirl.attributes_for(:evento, plantilla_id: plantilla.id, tipo: evento.tipo), :nodo_padre => myjstree1.id, :nodo_titulo => evento.nombre, :nodo_tipo => "evento_fin", :posicion => "0"}
        eventoBD = Evento.find_by_id(evento.id + 1)
        myjstreeBD = MyJsTree.last()
        post :destroy, {:id => eventoBD.id}
        response.should render_template(:text => "true")
      end
    end
  end
end
