=begin
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It     demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlantillasController do
  login_user

  describe "GET #index" do
    it "populates an array of plantillas" do
      tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
      plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
      get :index
      assigns(:plantillas).should eq([plantilla])
    end

    it "renders the :index view" do
      get :index
      response.should render_template :index
    end
  end

  describe "POST create" do
    context "with valid attributes" do
      it "creates a new plantilla" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        expect{
          post :create, {:idTart => "", plantilla: FactoryGirl.attributes_for(:plantilla, tipo_plantilla_id: tipo_plantilla.id)}
        }.to change(Plantilla,:count).by(1)
      end

      it "redirects to the new plantilla" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        post :create, {:idTart => "", plantilla: FactoryGirl.attributes_for(:plantilla, tipo_plantilla_id: tipo_plantilla.id)}
        response.should render_template :show
      end
    end
  end

  describe "POST update" do
    context "with valid attributes" do
      it "changes @plantilla's attributes" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantillaNew = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        plantillaUpdate = FactoryGirl.build(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        expect{
          post :create, {:idTart => plantillaNew.id, plantilla: FactoryGirl.attributes_for(:plantilla, nombre: plantillaUpdate.nombre, descripcion: plantillaUpdate.descripcion, tipo_plantilla_id: tipo_plantilla.id)}
        }.to change(Plantilla,:count).by(0)
        plantillaBD = Plantilla.find_by_id(plantillaNew.id)
        plantillaBD.nombre.should eq(plantillaUpdate.nombre)
        plantillaBD.descripcion.should eq(plantillaUpdate.descripcion)
      end

      it "redirects to the updated plantilla" do
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantillaNew = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        plantillaUpdate = FactoryGirl.build(:plantilla)
        post :create, {:idTart => plantillaNew.id, plantilla: FactoryGirl.attributes_for(:plantilla, nombre: plantillaUpdate.nombre, descripcion: plantillaUpdate.descripcion, tipo_plantilla_id: tipo_plantilla.id)}
        response.should render_template :index
      end
    end
  end
end
