=begin
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It     demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProyectosController do
  login_user

  describe "GET #index" do
    it "populates an array of proyectos" do
      proyecto = FactoryGirl.create(:proyecto)
      get :index
      assigns(:proyectos).should eq([proyecto])
    end

    it "renders the :index view" do
      get :index
      response.should render_template :index
    end
  end

  describe "POST create" do
    context "with valid attributes" do
      it "creates a new proyecto" do
        tipo_recurso = FactoryGirl.create(:tipo_recurso, unit: "1")
        usuario = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        expect{
          post :create, {:idTart => "", proyecto: FactoryGirl.attributes_for(:proyecto, director: usuario.id)}
        }.to change(Proyecto,:count).by(1)
      end

      it "redirects to the new proyecto" do
        tipo_recurso = FactoryGirl.create(:tipo_recurso, unit: "1")
        usuario = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        post :create, {:idTart => "", proyecto: FactoryGirl.attributes_for(:proyecto, director: usuario.id)}
        response.should render_template :index
      end
    end
  end

  describe "POST update" do
    context "with valid attributes" do
      it "changes @proyecto's attributes" do
        tipo_recurso = FactoryGirl.create(:tipo_recurso, unit: "1")
        usuario = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        usuario2 = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        proyectoNew = FactoryGirl.create(:proyecto, director: usuario.id)
        proyectoUpdate = FactoryGirl.build(:proyecto, director: usuario2.id)
        expect{
          post :create, {:idTart => proyectoNew.id, proyecto: FactoryGirl.attributes_for(:proyecto, nombre: proyectoUpdate.nombre, descripcion: proyectoUpdate.descripcion, director: proyectoUpdate.director, fecha_inicio: proyectoUpdate.fecha_inicio, fecha_fin: proyectoUpdate.fecha_fin)}
        }.to change(Proyecto,:count).by(0)
        proyectoBD = Proyecto.find_by_id(proyectoNew.id)
        proyectoBD.nombre.should eq(proyectoUpdate.nombre)
        proyectoBD.descripcion.should eq(proyectoUpdate.descripcion)
        proyectoBD.director.should eq(proyectoUpdate.director)
        proyectoBD.fecha_inicio.should eq(proyectoUpdate.fecha_inicio)
        proyectoBD.fecha_fin.should eq(proyectoUpdate.fecha_fin)
      end

      it "redirects to the updated proyecto" do
        tipo_recurso = FactoryGirl.create(:tipo_recurso, unit: "1")
        usuario = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        usuario2 = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        proyectoNew = FactoryGirl.create(:proyecto, director: usuario.id)
        proyectoUpdate = FactoryGirl.build(:proyecto, director: usuario2.id)
        post :create, {:idTart => proyectoNew.id, proyecto: FactoryGirl.attributes_for(:proyecto, nombre: proyectoUpdate.nombre, descripcion: proyectoUpdate.descripcion, director: proyectoUpdate.director, fecha_inicio: proyectoUpdate.fecha_inicio, fecha_fin: proyectoUpdate.fecha_fin)}
        response.should render_template :index
      end
    end
  end

  describe "POST overview" do
    context "with valid params" do
      it "asigns variables and renders the correct view" do
        tipo_recurso = FactoryGirl.create(:tipo_recurso, unit: "1")
        usuario = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        proyectoNew = FactoryGirl.create(:proyecto, director: usuario.id)
        post :overview, {:id => proyectoNew.id}
        response.should render_template :_overview
      end
    end
  end

  describe "POST configu" do
    context "with valid params" do
      it "asigns variables and renders the correct view" do
        tipo_recurso = FactoryGirl.create(:tipo_recurso, unit: "1")
        usuario = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        proyectoNew = FactoryGirl.create(:proyecto, director: usuario.id)
        post :configu, {:id => proyectoNew.id}
        response.should render_template :_configuracion
      end
    end
  end

  describe "POST priorizar" do
    context "with valid params" do
      it "priorizar" do
        tipo_recurso = FactoryGirl.create(:tipo_recurso, unit: "1")
        usuario = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        proyectoNew = FactoryGirl.create(:proyecto, director: usuario.id)
        post :priorizar, {:id => proyectoNew.id}
        response.should render_template :_priorizar
      end

      it "actualizarPriorizacion" do
        tipo_recurso2 = FactoryGirl.create(:tipo_recurso)
        tipo_recurso3 = FactoryGirl.create(:tipo_recurso)
        tipo_recurso4 = FactoryGirl.create(:tipo_recurso)
        tipo_recurso5 = FactoryGirl.create(:tipo_recurso)
        recurso = FactoryGirl.create(:recurso, tipo_recurso_id: tipo_recurso2.id, organizacion_id: @organizacionMaster.id)
        param = "qty_recurso_#{tipo_recurso3.id}"
        param1 = "qty_recurso_#{tipo_recurso5.id}"
        tipo_recurso = FactoryGirl.create(:tipo_recurso, unit: "1")
        usuario = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        proyecto = FactoryGirl.create(:proyecto, director: usuario.id)
        tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
        plantilla = FactoryGirl.create(:plantilla, tipo_plantilla_id: tipo_plantilla.id)
        myjstree = MyJsTree.new(:parent_id => 0,:position => 0,:type => 'root',:title => plantilla.nombre,:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree.save
        myjstree1 = MyJsTree.new(:parent_id => MyJsTree.last().id,:position => 0,:type => 'evento_inicio',:title => 'Inicio',:plantilla_id => plantilla.id,:left => 0,:right => 0,:level => 0)
        myjstree1.save
        proceso = FactoryGirl.create(:proceso, tipo_plantilla_id: tipo_plantilla.id, proyecto_id: proyecto.id)
        tarea = FactoryGirl.create(:tarea, proceso_id: proceso.id)
        tarea2 = FactoryGirl.create(:tarea, proceso_id: proceso.id)
        usuario2 = FactoryGirl.create(:usuario, tipo_recurso_id: tipo_recurso.id, organizacion_id: @organizacionMaster.id)
        tarea_participante = FactoryGirl.create(:tarea_participante, tarea_id: tarea.id, usuario_id: usuario2.id)
        tarea_participante2 = FactoryGirl.create(:tarea_participante, tarea_id: tarea2.id, usuario_id: usuario2.id)
        param = tarea2.id.to_s + ":" + tarea.id.to_s
        get :actualizarPriorizacion, {:tareas => param, :usu => usuario2.id, :id => "1"}
        tarea_participanteBD = TareaParticipante.find_by_id(tarea_participante.id)
        tarea_participanteBD2 = TareaParticipante.find_by_id(tarea_participante2.id)
        tarea_participanteBD.prioridad.should eq(2)
        tarea_participanteBD2.prioridad.should eq(1)
      end
    end
  end
end
