=begin
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It     demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipoPlantillasController do
  login_user

  describe "GET #index" do
    it "populates an array of tipo_plantillas" do
      tipo_plantilla = FactoryGirl.create(:tipo_plantilla)
      get :index
      assigns(:tipo_plantillas).should eq([tipo_plantilla])
    end

    it "renders the :index view" do
      get :index
      response.should render_template :index
    end
  end

  describe "POST create" do
    context "with valid attributes" do
      it "creates a new tipo_plantilla" do
        expect{
          post :create, {:idTart => "", tipo_plantilla: FactoryGirl.attributes_for(:tipo_plantilla)}
        }.to change(TipoPlantilla,:count).by(1)
      end

      it "redirects to the new tipo_plantilla" do
        post :create, {:idTart => "", tipo_plantilla: FactoryGirl.attributes_for(:tipo_plantilla)}
        response.should render_template :index
      end
    end
  end

  describe "POST update" do
    context "with valid attributes" do
      it "changes @tipo_plantilla's attributes" do
        tipo_plantillaNew = FactoryGirl.create(:tipo_plantilla)
        tipo_plantillaUpdate = FactoryGirl.build(:tipo_plantilla)
        expect{
          post :create, {:idTart => tipo_plantillaNew.id, tipo_plantilla: FactoryGirl.attributes_for(:tipo_plantilla, nombre: tipo_plantillaUpdate.nombre, descripcion: tipo_plantillaUpdate.descripcion)}
        }.to change(TipoPlantilla,:count).by(0)
        tipo_plantillaBD = TipoPlantilla.find_by_id(tipo_plantillaNew.id)
        tipo_plantillaBD.nombre.should eq(tipo_plantillaUpdate.nombre)
        tipo_plantillaBD.descripcion.should eq(tipo_plantillaUpdate.descripcion)
      end

      it "redirects to the updated tipo_plantilla" do
        tipo_plantillaNew = FactoryGirl.create(:tipo_plantilla)
        tipo_plantillaUpdate = FactoryGirl.build(:tipo_plantilla)
        post :create, {:idTart => tipo_plantillaNew.id, tipo_plantilla: FactoryGirl.attributes_for(:tipo_plantilla, nombre: tipo_plantillaUpdate.nombre, descripcion: tipo_plantillaUpdate.descripcion)}
        response.should render_template :index
      end
    end
  end
end
