=begin
    MONO
    Copyright (C) 2015  Universidad de los Andes
  
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It     demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipoOrganizacionsController do
  login_user

  describe "GET #index" do
    it "populates an array of tipo_organizacions" do
      #tipo_organizacion = FactoryGirl.create(:tipo_organizacion)
      get :index
      assigns(:tipo_organizacions).should eq([@tipo_organizacionMaster])
    end

    it "renders the :index view" do
      get :index
      response.should render_template :index
    end
  end

  describe "POST create" do
    context "with valid attributes" do
      it "creates a new tipo_organizacion" do
        expect{
          post :create, {:idTart => "", tipo_organizacion: FactoryGirl.attributes_for(:tipo_organizacion)}
        }.to change(TipoOrganizacion,:count).by(1)
      end

      it "redirects to the new tipo_organizacion" do
        post :create, {:idTart => "", tipo_organizacion: FactoryGirl.attributes_for(:tipo_organizacion)}
        response.should render_template :index
      end
    end
  end

  describe "POST update" do
    context "with valid attributes" do
      it "changes @tipo_organizacion's attributes" do
        tipo_organizacionNew = FactoryGirl.create(:tipo_organizacion)
        tipo_organizacionUpdate = FactoryGirl.build(:tipo_organizacion)
        expect{
          post :create, {:idTart => tipo_organizacionNew.id, tipo_organizacion: FactoryGirl.attributes_for(:tipo_organizacion, name: tipo_organizacionUpdate.name)}
        }.to change(TipoOrganizacion,:count).by(0)
        tipo_organizacionBD = TipoOrganizacion.find_by_id(tipo_organizacionNew.id)
        tipo_organizacionBD.name.should eq(tipo_organizacionUpdate.name)
      end

      it "redirects to the updated tipo_organizacion" do
        tipo_organizacionNew = FactoryGirl.create(:tipo_organizacion)
        tipo_organizacionUpdate = FactoryGirl.build(:tipo_organizacion)
        post :create, {:idTart => tipo_organizacionNew.id, tipo_organizacion: FactoryGirl.attributes_for(:tipo_organizacion, name: tipo_organizacionUpdate.name)}
        response.should render_template :index
      end
    end
  end
end
