source 'http://rubygems.org'

gem 'dropbox-sdk'
gem 'basecamp'
gem 'curl'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

#gem 'view_mapper'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'


 gem 'rspec-rails'
 gem 'cucumber-rails'
 gem 'capybara'
 gem 'database_cleaner'
 gem 'rdoc'
 gem 'paperclip'
 gem 'taskjuggler'
 gem 'wddx'
 gem 'json'
 gem 'rest-client'

 gem 'devise'
 gem 'cancan'
 gem 'rools'
 gem 'rgen'

gem 'table_builder'
gem 'simple_calendar'
gem "bunny", "~> 1.3.1"
gem 'daemons'
gem 'mechanize'
gem 'watir-webdriver'
gem 'selenium-webdriver'
gem 'headless'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'minitest-spec-rails'
  gem 'capybara_minitest_spec' # for capybara integration and spec matchers
  gem 'turn' # for prettier test output
end

group :test do
  gem 'faker'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'launchy'
end
